name: Jumping Bug CI/CD to EC2

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install Project Dependencies
        run: npm install
        working-directory: ./

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa libxi-dev

      - name: Build Cocos Creator Project
        run: |
          # Find the cocos executable path
          COCOS_PATH=$(find . -name cocos -type f -executable | head -n 1)

          if [ -z "$COCOS_PATH" ]; then
            echo "Cocos executable not found! Trying to run via npx..."
            npx --yes cocos build --platform web-mobile --output ./build/web-mobile
          else
            echo "Using cocos executable at: $COCOS_PATH"
            $COCOS_PATH build --platform web-mobile --output ./build/web-mobile
          fi
        working-directory: ./

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --delete -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./build/web-mobile/ $EC2_USER@$EC2_HOST:/var/www/jumping-bug/
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "sudo systemctl restart nginx"
          rm -f private_key.pem
