name: Jumping Bug CI/CD to EC2

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install Project Dependencies
        run: npm install
        working-directory: ./

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa libxi-dev

      - name: Download and Install Cocos Creator
        run: |
          # Download Cocos Creator
          wget https://digitalocean.cocos2d-x.org/Creator/v3.8.0/CocosCreator_v3.8.0_linux.run

          # Make it executable
          chmod +x CocosCreator_v3.8.0_linux.run

          # Install silently
          ./CocosCreator_v3.8.0_linux.run --mode unattended --install-dir ./cocos-creator

          # Add to PATH
          echo "$PWD/cocos-creator/CocosCreator.app/Contents/Resources/tools/creator-cli" >> $GITHUB_PATH

      - name: Build Cocos Creator Project
        run: |
          # Verify installation
          creator-cli --version

          # Run build
          creator-cli build --platform web-mobile --output ./build/web-mobile
        working-directory: ./

      - name: Verify Build Output
        run: |
          ls -la ./build/web-mobile
          [ -f ./build/web-mobile/index.html ] && echo "Build successful" || echo "Build failed"

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --delete -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./build/web-mobile/ $EC2_USER@$EC2_HOST:/var/www/jumping-bug/
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "sudo systemctl restart nginx"
          rm -f private_key.pem
